/**************************************************************************
 * C S 429 system emulator
 *
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>

#include "hw_elts.h"
#include "instr.h"
#include "instr_pipeline.h"

extern uint8_t D_src1, D_src2;

// LUT for extracting registers according to format.
extract_reg_func_t extract_regs_table[NUM_FORMATS];

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally.
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */
static comb_logic_t generate_DXMW_control(opcode_t op, d_ctl_sigs_t *D_sigs,
                                          x_ctl_sigs_t *X_sigs,
                                          m_ctl_sigs_t *M_sigs,
                                          w_ctl_sigs_t *W_sigs) {
    // Student TODO
    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format
 * instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */
static comb_logic_t extract_immval(uint32_t insnbits, opcode_t op,
                                   int64_t *imm) {
    switch (op)
    {
    case OP_ADD_RI:
        /* code */
        break;
    
    default:
        break;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    switch (op)
    {
        case OP_NOP:
        case OP_B:
        case OP_B_COND:
        case OP_BL:
        case OP_RET:
        case OP_HLT:
            *ALU_op = PASS_A_OP;
            break;
        
        case OP_LDUR:
        case OP_STUR:
        case OP_ADRP:
        case OP_ADD_RI:
        case OP_ADDS_RR:
        case OP_CMN_RR:
            *ALU_op = PLUS_OP;
            break;

        case OP_SUB_RI:
        case OP_SUBS_RR:
        case OP_CMP_RR:
            *ALU_op = MINUS_OP;
            break;

        case OP_ANDS_RR:
        case OP_TST_RR:
            *ALU_op = AND_OP;
            break;

        case OP_LSL_RI:
        case OP_LSL_RR:
            *ALU_op = LSL_OP;
            break;

        case OP_LSR_RI:
        case OP_LSR_RR:
            *ALU_op = LSR_OP;
            break;

        case OP_ASR:
            *ALU_op = ASR_OP;
            break;
        
        case OP_MVN:
            *ALU_op = INV_OP;
            break;
        
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;
        
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;

        case OP_MOVZ:
            *ALU_op = MOV_OP;
            break;

        case OP_MOVK:
            *ALU_op = MOVK_OP;
            break;
        
    default:
        break;
    }
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */
comb_logic_t copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    *dest = *src;
    return;
}

comb_logic_t copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    *dest = *src;
    return;
}

/*
 * Utility functions for extracting src1, src2, and dst registers.
 * STUDENT TO-DO:
 * Update fix_regs to determine whether 31 represents SP or XZR.
 */
comb_logic_t fix_regs(opcode_t op, uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

/*
 * Extract src1, src2, and dst registers from instruction. Do not modify.
 */
comb_logic_t extract_regs(uint32_t insnbits, opcode_t op, format_t format,
                          uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    extract_regs_table[format](insnbits, op, src1, src2, dst);
    fix_regs(op, src1, src2, dst);
    return;
}

/*
 * Pass through for FORMAT_ERROR. Do not modify.
 */
comb_logic_t format_other(uint32_t insnbits, opcode_t op, uint8_t *src1,
                          uint8_t *src2, uint8_t *dst) {
    return;
}

/*
 * Extract registers for each instruction format.
 * STUDENT TO-DO:
 * Fill out. Remember that some formats may not require any work.
 */
comb_logic_t format_m(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

comb_logic_t format_i1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

comb_logic_t format_i2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

comb_logic_t format_rr(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

comb_logic_t format_ri(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

comb_logic_t format_b1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

comb_logic_t format_b2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

comb_logic_t format_b3(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

/* For NOP/HLT instructions.
 */
comb_logic_t format_s(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    return;
}

#ifdef EC
/*
 * Extra credit instructions.
 */
comb_logic_t format_ec(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}
#endif

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 *
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 *
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval, extract_regs
 * and decide_alu_op.
 */
comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {

    out->op = in->op;
    out->print_op = in->print_op;
    out->multipurpose_val.seq_succ_PC = in->multipurpose_val.seq_succ_PC;
    decide_alu_op(in->op, out->ALU_op);

    return;
}
