/**************************************************************************
 * C S 429 system emulator
 *
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>

#include "hw_elts.h"
#include "instr.h"
#include "instr_pipeline.h"

extern uint8_t D_src1, D_src2;

// LUT for extracting registers according to format.
extract_reg_func_t extract_regs_table[NUM_FORMATS];

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally.
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */
static comb_logic_t generate_DXMW_control(opcode_t op, d_ctl_sigs_t *D_sigs,
                                          x_ctl_sigs_t *X_sigs,
                                          m_ctl_sigs_t *M_sigs,
                                          w_ctl_sigs_t *W_sigs) {
    // reset all signal to false
    D_sigs->src2_sel = false;
    X_sigs->set_flags = false;
    X_sigs->vala_sel = false;
    X_sigs->valb_sel = false;
    M_sigs->dmem_read = false;
    M_sigs->dmem_write = false;
    W_sigs->dst_sel = false;
    W_sigs->w_enable = false;
    W_sigs->wval_sel = false;

    D_sigs->src2_sel = op == OP_STUR;

    X_sigs->set_flags = op == OP_ADDS_RR || op == OP_CMN_RR || 
                        op == OP_SUBS_RR || op == OP_CMP_RR ||
                        op == OP_ANDS_RR || op == OP_TST_RR;
    X_sigs->vala_sel = op == OP_ADRP || op == OP_BL;
    X_sigs->valb_sel = ftable[op] == FORMAT_RR; 

    M_sigs->dmem_read = op == OP_LDUR;
    M_sigs->dmem_write = op == OP_STUR;
    
    W_sigs->dst_sel = op == OP_BL;
    W_sigs->w_enable = !(op == OP_NOP || op == OP_B || op == OP_B_COND || op == OP_STUR ||
                         op == OP_RET || op == OP_HLT || op == OP_ERROR || op == OP_CMP_RR || 
                         op == OP_CMN_RR);
    W_sigs->wval_sel = op == OP_LDUR;

    
    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format
 * instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */
static comb_logic_t extract_immval(uint32_t insnbits, opcode_t op,
                                   int64_t *imm) {
    switch (op) {
        case OP_LDUR:
        case OP_STUR:
            *imm = bitfield_s64(insnbits, 12, 9);
            break;
        case OP_MOVK:
        case OP_MOVZ:
            *imm = bitfield_u32(insnbits, 5, 16);
            break;
        case OP_ADD_RI:
        case OP_SUB_RI:
            *imm = bitfield_u32(insnbits, 10, 12);
            break;
        case OP_LSL_RI:
            *imm = 63 - bitfield_u32(insnbits, 10, 6);
            break;
        case OP_LSR_RI:
        case OP_ASR:
            *imm = bitfield_u32(insnbits, 16, 6);
            break;
        case OP_ADRP:
            int64_t immhi = bitfield_s64(insnbits, 5, 19);
            uint32_t immlo = bitfield_u32(insnbits, 29, 2);
            *imm = ((immhi << 2) | immlo) << 12;
            break;
        case OP_B:
            *imm = 0;
            break;
        case OP_BL:
            *imm = bitfield_s64(insnbits, 0, 26) << 2;
            break;
        case OP_B_COND:
            *imm = bitfield_s64(insnbits, 5, 19) << 2;
            break;
        default:
            break;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    switch (op)
    {
        case OP_NOP:
        case OP_B:
        case OP_B_COND:
        case OP_BL:
        case OP_RET:
        case OP_HLT:
            *ALU_op = PASS_A_OP;
            break;
        
        case OP_LDUR:
        case OP_STUR:
        case OP_ADRP:
        case OP_ADD_RI:
        case OP_ADDS_RR:
        case OP_CMN_RR:
            *ALU_op = PLUS_OP;
            break;

        case OP_SUB_RI:
        case OP_SUBS_RR:
        case OP_CMP_RR:
            *ALU_op = MINUS_OP;
            break;

        case OP_ANDS_RR:
        case OP_TST_RR:
            *ALU_op = AND_OP;
            break;

        case OP_LSL_RI:
        case OP_LSL_RR:
            *ALU_op = LSL_OP;
            break;

        case OP_LSR_RI:
        case OP_LSR_RR:
            *ALU_op = LSR_OP;
            break;

        case OP_ASR:
            *ALU_op = ASR_OP;
            break;
        
        case OP_MVN:
            *ALU_op = INV_OP;
            break;
        
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;
        
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;

        case OP_MOVZ:
            *ALU_op = MOV_OP;
            break;

        case OP_MOVK:
            *ALU_op = MOVK_OP;
            break;
        
    default:
        break;
    }
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */
comb_logic_t copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    *dest = *src;
    return;
}

comb_logic_t copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    *dest = *src;
    return;
}

/*
 * Utility functions for extracting src1, src2, and dst registers.
 * STUDENT TO-DO:
 * Update fix_regs to determine whether 31 represents SP or XZR.
 */
comb_logic_t fix_regs(opcode_t op, uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    // Student TODO
    switch (op) {
        case OP_ADD_RI:
        case OP_SUB_RI:
            // src1 and dst already holds SP = 31
            break;
        case OP_LDUR:
            // src1 cant be xzr
            if (*dst == 31) {
                *dst = XZR_NUM;
            }
            break;
        case OP_STUR:
            // src1 cant be xzr
            if (*src2 == 31) {
                *src2 = XZR_NUM;
            }
            break;
        case OP_CMP_RR:
            if (*src1 == 31) {
                *src1 = XZR_NUM;
            } 
            if (*src2 == 31) {
                *src2 = XZR_NUM;
            }
            *dst = 0;
            break;
        case OP_NOP:
        case OP_B_COND:
            *src1 = XZR_NUM;
            *src2 = XZR_NUM;
            break;
        default:
            // src1, src2, dst can be xzr or sp
            if (*src1 == 31) {
                *src1 = XZR_NUM;
            } 
            if (*src2 == 31) {
                *src2 = XZR_NUM;
            }
            if (*dst == 31) {
                *dst = XZR_NUM;
            }
            break;
    }
    return;
}

/*
 * Extract src1, src2, and dst registers from instruction. Do not modify.
 */
comb_logic_t extract_regs(uint32_t insnbits, opcode_t op, format_t format,
                          uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    extract_regs_table[format](insnbits, op, src1, src2, dst);
    fix_regs(op, src1, src2, dst);
    return;
}

/*
 * Pass through for FORMAT_ERROR. Do not modify.
 */
comb_logic_t format_other(uint32_t insnbits, opcode_t op, uint8_t *src1,
                          uint8_t *src2, uint8_t *dst) {
    return;
}

/*
 * Extract registers for each instruction format.
 * STUDENT TO-DO:
 * Fill out. Remember that some formats may not require any work.
 */
comb_logic_t format_m(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    *src1 = bitfield_u32(insnbits, 5, 5);
    // *src2 = XZR_NUM; // no src2 for M-format
    // *dst = bitfield_u32(insnbits, 0, 5);
    if (op == OP_STUR) {
        *dst = 0;
        *src2 = bitfield_u32(insnbits, 0, 5);
    } else {
        *dst = bitfield_u32(insnbits, 0, 5);
        *src2 = 0;
    }
    return;
}

comb_logic_t format_i1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = bitfield_u32(insnbits, 0, 5);
    *src2 = 0;
    *dst = *src1; // src1 and dst are the same for I1-format
    return;
}

comb_logic_t format_i2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // no src1 or src2 for I2-format
    *src1 = 0;
    *src2 = 0;
    *dst = bitfield_u32(insnbits, 0, 5);
    return;
}

comb_logic_t format_rr(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = bitfield_u32(insnbits, 5, 5); // Rn
    *src2 = bitfield_u32(insnbits, 16, 5); // Rm
    *dst = bitfield_u32(insnbits, 0, 5); // Rd
    return;
}

comb_logic_t format_ri(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // no src2 for RI-format
    *src1 = bitfield_u32(insnbits, 5, 5);
    *src2 = 31;
    *dst = bitfield_u32(insnbits, 0, 5);
    return;
}

comb_logic_t format_b1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // no src1 or src2 or dst 
    *src1 = 31; // set to xzr in fix_regs
    *src2 = 31;
    *dst = (op == OP_BL) ? 30 : 0;

    return;
}

comb_logic_t format_b2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // no src1 or src2 or dst 
    *src1 = 0;
    *src2 = 0;
    *dst = 0;
    return;
}

comb_logic_t format_b3(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // no src2 or dst
    *src1 = bitfield_u32(insnbits, 5, 5); // x30 for src1
    *src2 = 0;
    *dst = 0;
    return;
}

/* For NOP/HLT instructions.
 */
comb_logic_t format_s(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    // no src1 or src2 or dst for S-format
    *src1 = 0;
    *src2 = 0;
    *dst = 0;
    return;
}

#ifdef EC
/*
 * Extra credit instructions.
 */
comb_logic_t format_ec(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}
#endif

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 *
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 *
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval, extract_regs
 * and decide_alu_op.
 */
comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {
    // pass through opcode and format
    out->op = in->op;
    out->print_op = in->print_op;
    out->multipurpose_val.seq_succ_PC = in->multipurpose_val.seq_succ_PC;
    
    // control signals
    d_ctl_sigs_t d_ctl_sigs;
    generate_DXMW_control(in->op, &d_ctl_sigs, &out->X_sigs, &out->M_sigs, &out->W_sigs);
    
    // decides ALU op
    decide_alu_op(in->op, &out->ALU_op);

    // extract registers
    extract_regs(in->insnbits, in->op, in->format, &D_src1, &D_src2, &out->dst);

    // read register file
    out->val_a = 0;
    out->val_b = 0;
    if (in->op == OP_MOVZ) {
        D_src1 = XZR_NUM; 
    }
    if (out->op != OP_NOP && out->op != OP_HLT && out->op != OP_ERROR) {
        regfile_read(D_src1, D_src2, &out->val_a, &out->val_b);
    }

    // extract immediate values if have 
    out->val_imm = 0; // reset imm for instr that does not use it
    extract_immval(in->insnbits, in->op, &out->val_imm);
    if (out->op == OP_B_COND) { // set cond if operation was B.COND
        out->cond = bitfield_u32(in->insnbits, 0, 4);
        out->val_imm = 0;
    }
    if (out->op == OP_MOVK || out->op == OP_MOVZ) { // extract halfword for format I1
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) << 4;
    }

    out->status = in->status;
    return;
}
